baseurl: /
languageCode: en-us
title: Lima website
theme: "hugo-lithium"
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  # - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
# permalinks:
#     - post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: Portfolio
      url: /portfolio/
    - name: Network
      url: https://metabolomeconnectome.netlify.app/
    - name: Projects
      url: https://www.imim.cat/programesrecerca/neurociencies/es_metabolomica_aplicada.html?t=projectes&g=127/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Bla bla bla bla 3.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: 
    height: 50
    url: LOGO_lima.jpg
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
